### ISSUE TITLE
remove border from raking

### ISSUE THREAD

**Issue by JBenda** [t-erxleben/marbellous#114]
![image](https://user-images.githubusercontent.com/7237254/123549061-af71b480-d767-11eb-8840-6c7f2b8640b3.png)

there is a background color border around the canvas.

**Comment by t-erxleben** [comment]
Sry that's only my bad screenshot skills and part of the white website background.

**Comment by t-erxleben** [comment]
That reminds me of another task: We need to implement the download buttons for raked images.

**Comment by JBenda** [comment]
Oh, yes, it is white. This was hard to recognize.
