### ISSUE TITLE
Nails array broken

### ISSUE THREAD

**Issue by t-erxleben** [t-erxleben/marbellous#118]
Printing the rake pattern from front end yielded some interesting results. [rake_pattern.txt](https://github.com/t-erxleben/marbellous/files/6722043/rake_pattern.txt)
The output was generated with:
```
        for(int i = 0; i <1000; ++i) std::cout << nails[i] << ", ";
        std::cout << std::endl;
```
using nails directly from `rakeLinear`.

**Comment by JBenda** [comment]
fascinating
