### ISSUE TITLE
Documentation using Doxygen

### ISSUE THREAD

**Issue by t-erxleben** [t-erxleben/marbellous#41]
If it's not to much overhead we could generate docs with [Doxygen](https://github.com/doxygen/doxygen). Might be handy later on.

**Comment by JBenda** [comment]
True, and also Doxygen is human-readable in the code. 

I like to use something like below :)

```c++
/** summary, can also use a reference to @see foo().
 * detail explanation 
 * @tparam T template parameter description (also usable for classes)
 * @param arg1 desrciption
 * @param arg2 description
 * @return return value explained (only if needed)
 * @attention here write if something is unintuitive
 */
template<typename T> bool bar(int arg1, int arg2);
```

```c++
class BarFoo {
 /* stuff */
private:
   int m_size; ///< number of handled active elements (documentation for member)
};
```

**Comment by dknigs** [comment]
https://github.com/marketplace/actions/doxygen-action keeping this here for future reference, should be easily integrated into the existing github pages flow
