### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by t-erxleben** [t-erxleben/marbellous#74]
* [x] fix misspelling in footer
* [x] increase space between menu and canvas
* [x] add BG color option
* [x] spaces between buttons not equal in Chrome
* [x] Drops should resize in root (to emulate color flow)
* [x] rake pattern input field is clipped by window border
* [x] Make sidebar beautiful
* [x] change favicon
* [x] make input fields look nicer
* [x] leaving canvas while rake tool is active should end rake tool
* [x] clear-all button should set dropping state again
* [x] make canvas larger?
* [x] remove scrolling
* [x] realign notes to canvas

**removed**

* [ ] (not needed because colors are next to canvas)increase contrast from menu to canvas

**Comment by JBenda** [comment]
Contained in #130
