### ISSUE TITLE
Drawing artifacts

### ISSUE THREAD

**Issue by t-erxleben** [t-erxleben/marbellous#92]
I found a way to trigger some weird drawing. 
![artifact](https://user-images.githubusercontent.com/73595753/121754663-786b9400-cb15-11eb-9a3c-6b1ac240f1b2.png)
Dropping a new color drop exactly on the boundary of another drop of the same color produces a hard edge. This happens most likely because no actual new drop will be generated (due to the same color). The vertex insertion will than take place when actually dropping a new color drop. Until than the edge stays like this. 

I think a good fix would be to check vertex distances in each case in `addDrop`.

**Comment by JBenda** [comment]
sounds plausible, will check it out next sprint
